target := "riscv64imac-unknown-none-elf"
mode := "debug"
build-path := "../../target/" + target + "/" + mode + "/"
kernel-elf := build-path + "magic-return-kern"
kernel-bin := build-path + "magic-return-kern.bin"

objdump := "riscv64-unknown-elf-objdump"
objcopy := "rust-objcopy --binary-architecture=riscv64"
size := "rust-size"

build: firmware
    @{{objcopy}} {{kernel-elf}} --strip-all -O binary {{kernel-bin}}

firmware:
    @cargo build --target={{target}}

asm: build
    @{{objdump}} -D {{kernel-elf}} | less

size: build
    @{{size}} -A -x {{kernel-elf}} 
