target := "riscv64imac-unknown-none-elf"
mode := "debug"
build-path := "../target/" + target + "/" + mode + "/"
bootloader-bin := "../../rustsbi/target/" + target + "/debug/rustsbi-qemu.bin"
kernel-elf := build-path + "batch-kernel"
kernel-bin := build-path + "batch-kernel.bin"

threads := "1"

gdb := "riscv64-unknown-elf-gdb.exe"

run: kernel qemu

build app:
    @just -f "user/justfile" build {{app}}
    
kernel:
    @just -f "kernel/justfile" build

asm app:
    @just -f "user/justfile" asm {{app}}

size app:
    @just -f "user/justfile" size {{app}}

qemu: kernel
    @qemu-system-riscv64 \
            -machine virt \
            -nographic \
            -bios none \
            -device loader,file={{bootloader-bin}},addr=0x80000000 \
            -device loader,file={{kernel-bin}},addr=0x80200000 \
            -smp threads={{threads}}

debug: kernel
    @qemu-system-riscv64 \
            -machine virt \
            -nographic \
            -bios none \
            -device loader,file={{bootloader-bin}},addr=0x80000000 \
            -device loader,file={{kernel-bin}},addr=0x80200000 \
            -gdb tcp::1234 -S \
            -smp threads={{threads}}

gdb: 
    @{{gdb}} --eval-command="file {{kernel-elf}}" --eval-command="target remote localhost:1234"
