[package]
name = "complex-ctx-user"
version = "0.1.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r0 = "1"
buddy_system_allocator = "0.6"
spin = "0.7"
woke = "0.0.2"
